#!/bin/bash

# Written by Nika Prairie, 260843183 
# Ensure that the user passed in exactly two arguments, the 
# name of the project and the owner of the project
if [ "$#" -ne 2 ]; then
	echo "Error: Wrong number of arguments. Please type ./mkproj ARGUMENT OWNER. The argument is the name of the project. The OWNER is the user name the project belongs to."
	exit 1
fi

# If the Projects directory does not exist
# create it
if [ ! -d "$HOME/Projects" ]; then
       mkdir ~/Projects
fi 
# Change to the Projects directory in the user's home
# directory
cd ~/Projects

# If the project exists already, then go back to the parent
# directory and issue an error the user and exit
if [ -d "$1" ]; then  
	echo "Error: The project name has already been used. Please select another project name and try again."
	cd ..
	exit 1
fi

# Create the project directory and then go into it
mkdir "$1"

cd "$1"

# Create the sub-directories for the new project
mkdir archive
mkdir backup
mkdir docs
mkdir assets
mkdir database
mkdir source

# Display the new directories to the user
ls 

# Go into the documentation directory
# create a README file and then display
# the readme file to the user
cd docs

echo "Created by: $2" > readme.txt

cat readme.txt



